### ISSUE TITLE
Compiling with GCC 10.2

### ISSUE THREAD

**Issue by intendo** [Treecodes/TABI-PB#11]
@dvdesolve created a patch for the global variables used in the code:
https://aur.archlinux.org/cgit/aur.git/plain/globals_bem.patch?h=apbs

It has been tested with GCC 9.3 and 10.2 and compiles and passes the tests. The patch has been applied to the https://github.com/Electrostatics/TABIPB fork to get APBS to compile with GCC 10.2.

**Comment by lwwilson1** [comment]
Great, thank you for this. I'll pull it in from Electrostatics/TABIPB to lwwilson1/TABIPB to keep parity between the two. Fortunately I've removed all global variables from the new in-progress TABI-PB; I hope to have more to share with you on that soon.
