### ISSUE TITLE
Allow user to define output file names prefixes

### ISSUE THREAD

**Issue by jaredsagendorf** [Treecodes/TABI-PB#15]
Hello, currently TABI-PB outputs all its files with the same pre-defined prefix "output". This is bad practice because if running TABI-PI in parallel in the same directory (like on a dataset of proteins), the output files will collide with eachother.

A simple fix is to allow the user to define the prefix themselves.

**Comment by lwwilson1** [comment]
This is a long-standing kludge that was just never addressed. Thanks for pointing it out. Closed with PR #17 which adds `output_prefix` to control naming of output files for different runs
